import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconReportAnalytics,
  IconUsers,
  IconBriefcase,
  IconMessage2,
  IconChartBar,
  IconBuildingStore,
  IconCalendarEvent,
  IconClipboardList,
  IconCurrencyDollar,
  IconUserCheck,
  IconId,
  IconBuilding,
  IconHeadset,
  IconMail
} from '@tabler/icons-react';

import { IconProps } from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUsers,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  analytics: IconReportAnalytics,
  crm: IconBriefcase,
  messages: IconMessage2,
  chart: IconChartBar,
  store: IconBuildingStore,
  calendar: IconCalendarEvent,
  tasks: IconClipboardList,
  dollar: IconCurrencyDollar,
  userCheck: IconUserCheck,
  idCard: IconId,
  building: IconBuilding,
  headset: IconHeadset,
  mail: IconMail
};
